import argparse
import os
import subprocess
import time
from pathlib import Path

import psutil


def get_file_size(file_path: Path) -> int:
    return file_path.stat().st_size if file_path.exists() else 0


def monitor_process(process: subprocess.Popen) -> dict:
    cpu_percentages = []
    memory_usages = []
    try:
        proc = psutil.Process(process.pid)
        proc.cpu_percent(interval=None)
        while process.poll() is None:
            cpu_percentages.append(proc.cpu_percent(interval=0.1))
            memory_usages.append(proc.memory_info().rss / 1024 / 1024)
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass

    return {
        "avg_cpu": sum(cpu_percentages) / len(cpu_percentages) if cpu_percentages else 0.0,
        "max_memory": max(memory_usages) if memory_usages else 0.0,
    }


def decompress(input_path: Path, output_dir: Path) -> dict:
    cmd = [
        "python",
        "main_new.py",
        "--compressor",
        "Lossless",
        "--input_path",
        str(input_path),
        "--output_path",
        str(output_dir),
        "--mode",
        "d",
    ]

    start_time = time.time()
    process = subprocess.Popen(cmd)
    metrics = monitor_process(process)
    process.wait()
    end_time = time.time()

    time.sleep(1)

    compressed_size = get_file_size(input_path)
    stem = input_path.stem
    candidate_fastq = output_dir / f"{stem}.fastq"
    if not candidate_fastq.exists():
        fastq_candidates = sorted(
            [p for p in output_dir.glob("*.fastq") if p.is_file()],
            key=lambda p: p.stat().st_size,
            reverse=True,
        )
        if fastq_candidates:
            candidate_fastq = fastq_candidates[0]

    decompressed_size = get_file_size(candidate_fastq)
    elapsed = end_time - start_time
    speed = (decompressed_size / 1024 / 1024) / elapsed if elapsed > 0 else 0.0

    return {
        "compressed_size_mb": compressed_size / 1024 / 1024,
        "decompressed_size_mb": decompressed_size / 1024 / 1024,
        "decompress_time_s": elapsed,
        "decompress_speed_mbs": speed,
        "avg_cpu_percent": metrics["avg_cpu"],
        "max_memory_mb": metrics["max_memory"],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Decompress a lossless archive generated by LossLess_thread")
    parser.add_argument("--input_path", required=True, help="Compressed lossless file")
    parser.add_argument("--output_path", required=True, help="Directory for the decompressed FASTQ")
    args = parser.parse_args()

    input_path = Path(args.input_path)
    output_dir = Path(args.output_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    metrics = decompress(input_path, output_dir)

    print("Decompression finished.")
    print(f"Compressed size: {metrics['compressed_size_mb']:.2f} MB")
    print(f"Decompressed size: {metrics['decompressed_size_mb']:.2f} MB")
    print(f"Time: {metrics['decompress_time_s']:.2f} s")
    print(f"Speed: {metrics['decompress_speed_mbs']:.2f} MB/s")
    print(f"Avg CPU: {metrics['avg_cpu_percent']:.2f}%")
    print(f"Max RSS: {metrics['max_memory_mb']:.2f} MB")


if __name__ == "__main__":
    main()
